imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    ## Landings:
    - { resource: parameters/landings/landings.yml, ignore_errors: true }
    - { resource: parameters/landings/precios_especiales.yml, ignore_errors: true }
    - { resource: parameters/landings/buenos_pagadores.yml, ignore_errors: true }
    - { resource: parameters/landings/renuncias.yml, ignore_errors: true }
    ## Productos:
    - { resource: parameters/sections/hogar/laptops.yml, ignore_errors: true }
    - { resource: parameters/sections/hogar/smarttvs.yml, ignore_errors: true }
    - { resource: parameters/sections/hogar/tecnologia.yml, ignore_errors: true }
    - { resource: parameters/sections/movil/postpago.yml, ignore_errors: true }
    - { resource: parameters/sections/movil/tablets.yml, ignore_errors: true }
    - { resource: parameters/sections/technology/iot.yml, ignore_errors: true }
    - { resource: parameters/sections/movil/tarifario.yml, ignore_errors: true }
    ## Home:
    - { resource: parameters/sections/home/home.yml, ignore_errors: true }
    - { resource: parameters/sections/home/calugas.yml, ignore_errors: true }
    - { resource: parameters/sections/home/vitrina.yml, ignore_errors: true }
    - { resource: parameters/sections/home/metadata.yml, ignore_errors: true }
    ## Planes Móviles:
    - { resource: parameters/sections/movil/planesmoviles.yml, ignore_errors: true }
    - { resource: parameters/sections/movil/portabilidad.yml }
    ## Servicios Hogar:
    - { resource: parameters/sections/hogar/servicioshogar.yml, ignore_errors: true }
    ## Ofertas:
    - { resource: parameters/sections/ofertas/ofertas.yml, ignore_errors: true }
    - { resource: parameters/sections/ofertas/clientes_claro.yml, ignore_errors: true }
    - { resource: parameters/sections/ofertas/sin_cuota_inicial.yml, ignore_errors: true }
    - { resource: parameters/sections/ofertas/catalogo_qr.yml, ignore_errors: true }
    ## Ofertas personalizadas:
    - { resource: parameters/sections/ofertas/custom/apple_gigas_gratis.yml, ignore_errors: true }
    - { resource: parameters/sections/promociones/whatsapp.yml, ignore_errors: true }
    ## Carrito:
    - { resource: parameters/sections/carrito/carrito.yml, ignore_errors: true }
    - { resource: parameters/sections/carrito/notifications.yml, ignore_errors: true }
    - { resource: parameters/sections/carrito/kushki.yml, ignore_errors: true }
    - { resource: parameters/sections/carrito/placetopay.yml, ignore_errors: true }
    - { resource: parameters/sections/carrito/jit.yml, ignore_errors: true }
    - { resource: parameters/sections/carrito/prioritarios.yml, ignore_errors: true }
    - { resource: parameters/sections/carrito/reservas.yml, ignore_errors: true }
    ## API, Feed and other:
    - { resource: parameters/external/webservice.yml, ignore_errors: true }
    - { resource: parameters/external/carrusel.yml, ignore_errors: true }
    - { resource: parameters/external/fbMarketPlace.yml, ignore_errors: true }
    - { resource: parameters/external/chat_ventas.yml, ignore_errors: true }
    ## Pymes:
    - { resource: parameters/sections/pymes/planes_moviles.yml, ignore_errors: true }
    ## General:
    - { resource: parameters/sections/global/tags.yml, ignore_errors: true }
    - { resource: parameters/sections/global/menu.yml, ignore_errors: true }
    - { resource: parameters/sections/global/extras.yml, ignore_errors: true }
    - { resource: parameters/sections/global/promocionales.yml, ignore_errors: true }
# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        domainProtocol:      "%domainProtocol%"
        domainServer:        "%domainServer%"
        domainServerImg:     "%domainServerImg%"

# Doctrine Configuration
doctrine:
    dbal:
        driver: '%database_driver%'
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
