Dayscript\TiendaClaroBundle\Entity\CustomPlanFijo:
    type: entity
    table: cus__pl_fijos
    indexes:
        IDX_A17B4F39567A477F:
            columns:
                - id_plan
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        orden:
            type: integer
            length: 50
            column: orden
        subtipo:
            type: string
            nullable: true
            length: 50
            fixed: false
            column: subtipo
        incluye:
            type: text
            nullable: true
            fixed: false
            column: incluye
        promocion:
            type: text
            nullable: true
            fixed: false
            column: promocion
        imgDetalle:
            type: text
            nullable: true
            fixed: false
            column: img_detalle
        descripcion:
            type: string
            nullable: true
            length: 50
            fixed: false
            column: descripcion
    oneToOne:
        plan:
            targetEntity: StoPlan
            inversedBy: customPlanFijo
            joinColumn:
                name: id_plan
                referencedColumnName: id
    manyToOne:
        idPlan:
            targetEntity: StoPlan
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_plan:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
