Dayscript\TiendaClaroBundle\Entity\GenPlanDetalle:
    type: entity
    table: gen__plan_detalles
    indexes:
        IDX_68BE2230FB0D0145:
            columns:
                - id_tipo
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        descripcion:
            type: string
            nullable: true
            length: 255
            fixed: false
        rutaImg:
            type: text
            nullable: true
            length: null
            fixed: false
            column: ruta_img
        orden:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
        isGb:
            type: boolean
            nullable: false
            default: false
            column: is_gb
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        deletedAt:
            type: datetime
            nullable: true
            column: deleted_at
    manyToOne:
        idTipo:
            targetEntity: TipoPlanDetalle
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_tipo:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
