Dayscript\TiendaClaroBundle\Entity\RegPortabilidadNumero:
    type: entity
    table: reg__port_numeros
    indexes:
        IDX_19961985AC198A8E:
            columns:
                - id_portabilidad
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        formCodigo:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: form_codigo
        numero:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        nip:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
        nipRequestedAt:
            type: datetime
            nullable: true
            column: nip_requested_at
        nipValidatedAt:
            type: datetime
            nullable: true
            column: nip_validated_at
        isNipValidado:
            type: boolean
            nullable: false
            options:
                default: false
            column: is_nip_validado
        isConfirmado:
            type: boolean
            nullable: false
            options:
                default: false
            column: is_confirmado
        createdAt:
            type: datetime
            nullable: false
            default: CURRENT_TIMESTAMP
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            default: CURRENT_TIMESTAMP
            column: updated_at
        expiresAt:
            type: datetime
            nullable: false
            column: expires_at
        deletedAt:
            type: datetime
            nullable: true
            column: deleted_at
    manyToOne:
        idPortabilidad:
            targetEntity: RegPortabilidad
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_portabilidad:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
