Dayscript\TiendaClaroBundle\Entity\RegPortabilidadAnexo:
    type: entity
    table: reg__port_anexos
    indexes:
        IDX_2904B81AAC198A8E:
            columns:
                - id_portabilidad
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        formCodigo:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: form_codigo
        tipo:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        ruta:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        rutaReal:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
            column: ruta_real
        isConfirmado:
            type: boolean
            nullable: false
            options:
                default: false
            column: is_confirmado
        isEnviado:
            type: boolean
            nullable: false
            options:
                default: false
            column: is_enviado
        createdAt:
            type: datetime
            nullable: false
            default: CURRENT_TIMESTAMP
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            default: CURRENT_TIMESTAMP
            column: updated_at
        expiresAt:
            type: datetime
            nullable: false
            column: expires_at
        deletedAt:
            type: datetime
            nullable: true
            column: deleted_at
    manyToOne:
        idPortabilidad:
            targetEntity: RegPortabilidad
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_portabilidad:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
