Dayscript\TiendaClaroBundle\Entity\TipoTransaccion:
    type: entity
    table: tipo__transacciones
    repositoryClass: Dayscript\TiendaClaroBundle\Entity\TipoTransaccionRepository
    indexes:
        IDX_AA6E33D3ABB54A09:
            columns:
                - id_negocio
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        slug:
            type: string
            nullable: false
            length: 100
            fixed: false
        nombre:
            type: string
            nullable: false
            length: 100
            fixed: false
        descripcion:
            type: string
            nullable: true
            length: 255
            fixed: false
        checkMetodo:
            type: boolean
            nullable: false
            default: true
            column: check_metodo
        isVenta:
            type: boolean
            nullable: false
            default: true
            column: is_venta
        hasPlan:
            type: boolean
            nullable: false
            default: true
            column: has_plan
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        deletedAt:
            type: datetime
            nullable: true
            column: deleted_at
    manyToOne:
        idNegocio:
            targetEntity: TipoNegocio
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_negocio:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        planDetalles:
            targetEntity: StoPlanDetalle
            mappedBy: transaccion
    lifecycleCallbacks: {  }
