Dayscript\TiendaClaroBundle\Entity\TipoNegocio:
    type: entity
    table: tipo__negocios
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        codigo:
            type: string
            nullable: false
            length: 20
            fixed: false
        nombre:
            type: string
            nullable: false
            length: 100
            fixed: false
        descripcion:
            type: string
            nullable: true
            length: 255
            fixed: false
        rutaThumb:
            type: text
            nullable: true
            length: null
            fixed: false
            column: ruta_thumb
        rutaImg:
            type: text
            nullable: true
            length: null
            fixed: false
            column: ruta_img
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        deletedAt:
            type: datetime
            nullable: true
            column: deleted_at
    lifecycleCallbacks: {  }
