Dayscript\TiendaClaroBundle\Entity\TipoPlanDetalle:
    type: entity
    table: tipo__plan_detalles
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        slug:
            type: string
            nullable: false
            length: 50
            fixed: false
        nombre:
            type: string
            nullable: false
            length: 100
            fixed: false
        descripcion:
            type: string
            nullable: true
            length: 255
            fixed: false
        orden:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        deletedAt:
            type: datetime
            nullable: true
            column: deleted_at
    lifecycleCallbacks: {  }
